# Generated by Django 2.2.7 on 2020-01-10 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('lecturer', models.ManyToManyField(blank=True, related_name='lecturer', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True)),
                ('role', models.CharField(choices=[('S', 'Student'), ('L', 'Lecturer')], max_length=1, null=True)),
                ('student_group', models.CharField(blank=True, choices=[('G1', 'Group 1'), ('G2', 'Group 2'), ('G3', 'Group 3')], max_length=2, null=True)),
                ('image', models.ManyToManyField(blank=True, to='attendiApp.Media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_percentage', models.FloatField()),
                ('courses_missed', models.PositiveIntegerField()),
                ('time_in_courses', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendiApp.Course')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendiApp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('V1', 'Vorlesungssaal 1'), ('V2', 'Vorlesungssaal 2'), ('V3', 'Vorlesungssaal 3'), ('V4', 'Vorlesungssaal 4'), ('V5', 'Vorlesungssaal 5'), ('S1', 'Seminarraum 18'), ('S2', 'Seminarraum 19'), ('L1', 'EDV-Labor 31'), ('L2', 'EDV-Labor 33'), ('L3', 'EDV-Labor 41'), ('L4', 'EDV-Labor 45')], max_length=2, null=True)),
                ('mandatory', models.BooleanField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendiApp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('absence_note', models.ManyToManyField(blank=True, to='attendiApp.Media')),
                ('course_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendiApp.CourseSession')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
