# Generated by Django 2.2.7 on 2020-01-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesession',
            name='student_group',
            field=models.CharField(choices=[('L', 'Lecturer'), ('G1', 'Group 1'), ('G2', 'Group 2'), ('G3', 'Group 3')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_group',
            field=models.CharField(blank=True, choices=[('L', 'Lecturer'), ('G1', 'Group 1'), ('G2', 'Group 2'), ('G3', 'Group 3')], max_length=2, null=True),
        ),
    ]
