# Generated by Django 2.2.7 on 2020-01-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file',
        ),
        migrations.RemoveField(
            model_name='media',
            name='file_title',
        ),
        migrations.AddField(
            model_name='media',
            name='content_type',
            field=models.TextField(default='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='original_file_name',
            field=models.TextField(default='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='size',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
