# Generated by Django 2.2.6 on 2020-01-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendiApp', '0003_auto_20200121_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesession',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
