# Generated by Django 2.2.7 on 2020-01-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendiApp', '0003_auto_20200113_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ManyToManyField(blank=True, to='attendiApp.Media'),
        ),
    ]
