# Generated by Django 2.2.7 on 2020-01-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendiApp', '0006_auto_20200113_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='content_type',
            field=models.TextField(default='png'),
            preserve_default=False,
        ),
    ]
