# Generated by Django 2.2.7 on 2020-01-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendiApp', '0007_media_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
