# Generated by Django 2.2.6 on 2020-01-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendiApp', '0008_coursesession_studentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='password',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
