# Generated by Django 2.2.7 on 2020-01-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendiApp', '0008_remove_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='student_group',
            field=models.CharField(choices=[('G1', 'Group 1'), ('G2', 'Group 2'), ('G3', 'Group 3')], max_length=2, null=True),
        ),
    ]
