# Generated by Django 3.0.2 on 2020-01-04 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('lecturer', models.ManyToManyField(blank=True, related_name='lecturer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.TextField()),
                ('content_type', models.TextField()),
                ('size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_percentage', models.FloatField()),
                ('courses_missed', models.PositiveIntegerField()),
                ('time_in_courses', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendi.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('role', models.CharField(choices=[('S', 'Student'), ('L', 'Lecturer')], max_length=1, null=True)),
                ('student_group', models.CharField(choices=[('G1', 'Group 1'), ('G2', 'Group 2'), ('G3', 'Group 3')], max_length=2, null=True)),
                ('image', models.ManyToManyField(blank=True, null=True, to='attendi.Media')),
                ('statistics', models.ManyToManyField(blank=True, null=True, to='attendi.Statistic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('V1', 'Vorlesungssaal 1'), ('V2', 'Vorlesungssaal 2'), ('V3', 'Vorlesungssaal 3'), ('V4', 'Vorlesungssaal 4'), ('V5', 'Vorlesungssaal 5'), ('S1', 'Seminarraum 18'), ('S2', 'Seminarraum 19'), ('L1', 'EDV-Labor 31'), ('L2', 'EDV-Labor 33'), ('L3', 'EDV-Labor 41'), ('L4', 'EDV-Labor 45')], max_length=2, null=True)),
                ('mandatory', models.BooleanField()),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('attendance_list', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendi.AttendanceItem')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendi.CourseSession'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceitem',
            name='absence_note',
            field=models.ManyToManyField(blank=True, to='attendi.Media'),
        ),
        migrations.AddField(
            model_name='attendanceitem',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
