# Generated by Django 3.0.2 on 2020-01-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ManyToManyField(blank=True, to='attendi.Media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='statistics',
            field=models.ManyToManyField(blank=True, to='attendi.Statistic'),
        ),
    ]
