# Generated by Django 3.0.2 on 2020-01-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendi', '0002_auto_20200104_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceitem',
            name='status',
        ),
        migrations.AddField(
            model_name='attendanceitem',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
